### ISSUE TITLE
Update to cloud API v1beta1?

### ISSUE THREAD

**Issue by lierdakil** [neal/OpalX#15]
Hi, I know that it's not officially released yet, but it's already possible to get API key,  so do you plan on updating to use https://api.lifx.com/? Since lifx-http is pretty much broken with 2.0 firmare...

**Comment by lierdakil** [comment]
Hello?

**Comment by neal** [comment]
Sorry for taking so long. I do plan on updating it, just not sure when. Pull requests are much welcome :)

**Comment by lierdakil** [comment]
ETIMEDOUT
